CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(16) NOT NULL DEFAULT 'user',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actor VARCHAR(255) NOT NULL,
  action VARCHAR(255) NOT NULL,
  details TEXT
);

ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS actor VARCHAR(255) NOT NULL DEFAULT 'system';
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS action VARCHAR(255) NOT NULL DEFAULT 'unknown';
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS details TEXT NULL;
ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
